config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'single_player', to: 'games#single_player'
  get 'new_world', to: 'games#new_world'
  get 'users/achievements', to: 'users#achievements', as: 'achievements'
  post 'worlds', to: 'games#create'
  get 'games/:id', to: 'games#show', as: 'game'
  delete 'single_player/:id', to: 'games#destroy', as: 'destroy'
  resources :worlds, only: [:create]

  root 'home#index'

  resources :games do
    member do
      post :join
    end
  end

  resources :worlds do
    post 'move', on: :member
    get 'resolve_battle', on: :member
    post 'attack_with_item', on: :member
    post 'shard_move', on: :member
    post 'acknowledge_encounter', on: :member
  end

  get 'shards/purchase', to: 'shards#new', as: 'new_shards_purchase'
  post 'shards/purchase', to: 'shards#create', as: 'shards_purchase'
  post 'shards/fetch_rate', to: 'shards#fetch_rate'

  resources :shop, only: [:index]
  post 'shop/buy/:id', to: 'shop#buy', as: 'buy_item'

  get 'user/inventory', to: 'users#inventory', as: 'user_inventory'

  get 'profile', to: 'users#show', as: 'user_profile'

  resources :users do
    collection do
      post 'claim_achievement', to: 'users#claim_achievement'
    end
  end
end

app/controllers/shop_controller.rb
# frozen_string_literal: true

class ShopController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.where.not(name: 'Basic Dagger')
  end

  def buy
    item = Item.find(params[:id])

    user_item = current_user.user_items.find_by(item: item)

    if user_item
      sell_item(user_item)
    else
      buy_new_item(item)
    end

    redirect_to shop_index_path
  end

  private

  def buy_new_item(item)
    if current_user.shards_balance >= item.price
      current_user.decrement!(:shards_balance, item.price)

      current_user.user_items.create(item: item)

      flash[:notice] = "Successfully bought #{item.name}!"
    else
      flash[:alert] = 'Not enough shards!'
    end
  end

  def sell_item(user_item)
    refund_amount = (user_item.item.price * 0.75).round
    current_user.increment!(:shards_balance, refund_amount)

    user_item.destroy

    flash[:notice] = "Successfully sold #{user_item.item.name} for #{refund_amount} Shards!"
  end
end

app/helpers/shop_helper.rb
# frozen_string_literal: true

module ShopHelper
end

app/views/shop/buy.html.erb
<h1>Shop#buy</h1>
<p>Find me in app/views/shop/buy.html.erb</p>

app/views/shop/index.html.erb
<h1 class="text-center mb-4 mt-4">Shop</h1>

<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @items.each do |item| %>
      <div class="col">
        <div class="card shadow-sm h-100">
          <div class="d-flex justify-content-center align-items-center bg-white" style="height: 200px;">
            <%= image_tag item.image_url, class: 'card-img-top', alt: item.name, style: 'max-height: 100%; max-width: 100%; object-fit: contain;' %>
          </div>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= item.name %></h5>
            <p class="card-text mb-3"><%= item.description %></p>
            <p class="card-text mb-3"><strong>Price: <%= item.price %> Shards</strong></p>
            <p class="card-text mb-3"><strong>Damage: <%= item.damage %></strong></p>

            <% user_item = current_user.user_items.find_by(item: item) %>

            <% if user_item %>
              <%= button_to 'Sell', buy_item_path(item.id), method: :post, class: 'btn btn-warning w-100' %>
              <p class="text-muted text-center mt-2">Sell for <%= (item.price * 0.75).round %> Shards</p>
            <% else %>
              <%= button_to 'Buy', buy_item_path(item.id), method: :post, class: 'btn btn-primary w-100' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>