config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'single_player', to: 'games#single_player'
  get 'new_world', to: 'games#new_world'
  get 'users/achievements', to: 'users#achievements', as: 'achievements'
  post 'worlds', to: 'games#create'
  get 'games/:id', to: 'games#show', as: 'game'
  delete 'single_player/:id', to: 'games#destroy', as: 'destroy'
  resources :worlds, only: [:create]

  root 'home#index'

  resources :games do
    member do
      post :join
    end
  end

  resources :worlds do
    post 'move', on: :member
    get 'resolve_battle', on: :member
    post 'attack_with_item', on: :member
    post 'shard_move', on: :member
    post 'acknowledge_encounter', on: :member
  end

  get 'shards/purchase', to: 'shards#new', as: 'new_shards_purchase'
  post 'shards/purchase', to: 'shards#create', as: 'shards_purchase'
  post 'shards/fetch_rate', to: 'shards#fetch_rate'

  resources :shop, only: [:index]
  post 'shop/buy/:id', to: 'shop#buy', as: 'buy_item'

  get 'user/inventory', to: 'users#inventory', as: 'user_inventory'

  get 'profile', to: 'users#show', as: 'user_profile'

  resources :users do
    collection do
      post 'claim_achievement', to: 'users#claim_achievement'
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<div class="container text-center mt-5">
  <div class="jumbotron bg-light shadow rounded p-3" style="background: url('<%= asset_path 'dungeon_bg.jpg' %>') no-repeat center center; background-size: cover; height: auto; min-height: 400px;">
    <h1 class="display-4 text-white">Shards of the Grid</h1>
    <p class="lead text-white">Embark on epic adventures and forge your path in new worlds!</p>
    <div class="d-flex justify-content-center mt-3">
      <div class="mx-2">
        <%= button_to 'View Games', single_player_path, method: :get, class: 'btn btn-primary btn-lg' %>
      </div>
      <div class="mx-2">
        <%= button_to 'Create New World', new_world_path, method: :get, class: 'btn btn-success btn-lg' %>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body">
          <i class="fas fa-map-marked-alt fa-3x text-primary mb-3"></i>
          <h5 class="card-title">Explore Worlds</h5>
          <p class="card-text">Join new worlds or revisit your saved ones!</p>
          <%= button_to 'View Games', single_player_path, method: :get, class: 'btn btn-outline-primary btn-sm' %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body">
          <i class="fas fa-globe fa-3x text-success mb-3"></i>
          <h5 class="card-title">Create a World</h5>
          <p class="card-text">Create a new and unique fantasy world!</p>
          <%= button_to 'Create New World', new_world_path, method: :get, class: 'btn btn-outline-success btn-sm' %>
        </div>
      </div>
    </div>
  </div>

  <footer class="mt-4">
    <p class="text-muted">&copy; Shards of the Grid</p>
  </footer>
</div>