config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'single_player', to: 'games#single_player'
  get 'new_world', to: 'games#new_world'
  get 'users/achievements', to: 'users#achievements', as: 'achievements'
  post 'worlds', to: 'games#create'
  get 'games/:id', to: 'games#show', as: 'game'
  delete 'single_player/:id', to: 'games#destroy', as: 'destroy'
  resources :worlds, only: [:create]

  root 'home#index'

  resources :games do
    member do
      post :join
    end
  end

  resources :worlds do
    post 'move', on: :member
    get 'resolve_battle', on: :member
    post 'attack_with_item', on: :member
    post 'shard_move', on: :member
    post 'acknowledge_encounter', on: :member
  end

  get 'shards/purchase', to: 'shards#new', as: 'new_shards_purchase'
  post 'shards/purchase', to: 'shards#create', as: 'shards_purchase'
  post 'shards/fetch_rate', to: 'shards#fetch_rate'

  resources :shop, only: [:index]
  post 'shop/buy/:id', to: 'shop#buy', as: 'buy_item'

  get 'user/inventory', to: 'users#inventory', as: 'user_inventory'

  get 'profile', to: 'users#show', as: 'user_profile'

  resources :users do
    collection do
      post 'claim_achievement', to: 'users#claim_achievement'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shards of the Grid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-between">
        <div class="navbar-brand">
          <%= link_to "Shards of the Grid", root_path, class: "navbar-logo text-white" %>
        </div>
        <ul class="navbar-nav d-flex align-items-center ml-auto gap-4">
          <li class="nav-item mr-3"><%= link_to "Home", root_path, class: "nav-link text-white" %></li>
          <% if user_signed_in? %>
            <li class="nav-item mr-3"><%= link_to "Inventory", user_profile_path, class: "nav-link text-white" %></li>
            <li class="nav-item mr-3"><%= link_to "Item Shop", shop_index_path, class: "nav-link text-white" %></li>
            <li class="nav-item mr-3"><%= link_to "Buy Shards", new_shards_purchase_path, class: "nav-link text-white" %></li>
            <li class="nav-item mr-3"><%= link_to "Achievements", achievements_path, class: "nav-link text-white" %></li>
            <li class="nav-item mr-3">
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link button-link text-white bg-danger" %>
            </li>
            <li class="nav-item">
              <span class="navbar-text text-white">💎 Shards: <%= current_user.shards_balance %></span>
            </li>
          <% else %>
            <li class="nav-item mr-3"><%= link_to "Sign In", new_user_session_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white nav-link-signup" %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <% if flash[:notice] %>
      <div class="flash notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash alert"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>